### ISSUE TITLE
Doesn't work on tweetdeck

### ISSUE THREAD

**Issue by piccolbo** [polomarcus/faster-links#7]
Hi,
I installed the extension in the latest chrome, os x yosemite. I can see the extension is working on twitter but not tweetdeck. It seems to me the extension promises to replace t.co link wherever they happen to be. Am I right? Thanks

**Comment by polomarcus** [comment]
Hi @piccolbo,

You're right, it removes `t.co` links but also it replaces every shortened URLS such as `bit.ly` with their real URLs, and finally it shows you the URL in full length so you can know where your click is going to bring you :smile: 

It's only on activated _Twitter_ right now :  https://github.com/polomarcus/faster-links/blob/master/app/scripts.babel/contentscript.js#L153 

I can make it work on Tweedeck, I will open a PR thanks for you proposing :+1:

**Comment by piccolbo** [comment]
Would it be possible to activate it for every site? Isn't URL shortening bad everywhere? Not sure how general your approach is.

**Comment by polomarcus** [comment]
You have a point there. 

The only thing is Faster Links [only targets "a" HTML tags that contains an external link](https://github.com/polomarcus/faster-links/pull/8/commits/234f47d2ec5ded08394db7f15bd5fb9c8137bf54#diff-5feac6cb4cde83d2ee21c4deb0a9f993R169) for Tweeter or DeckTweet to avoid useless CPU usage for example and keep your browser fast. :rocket: 

So it might be hard to keep this clean targetting and use the extension on every site. But I will think about it.

You can find the newest version (1.0.4) compatible with TweetDeck [on the Chrome store](https://chrome.google.com/webstore/detail/fasterlinks/ojggkiabpbjlckhpaphgdhhojgcpimah) or if you have already the extension it will be automatically updated in the next hours/days :smile:
